name_tool = "Red Tiger"
version_tool = "2.3.0"
coding_tool = "Python"
language_tool = "EN"
creator = "FluzyTeck"
discord_server = "discord.gg/eWNQ46jqdC"
website = "red-tiger.000webhostapp.com/accueil.html"
github_tool = "github.com/fluzyteck/RedTiger"
url_config = "https://raw.githubusercontent.com/fluzyteck/RedTiger/main/Settings/Program/Config/Config.py"

