name_tool = "RedTiger"
version_tool = "2.9"
coding_tool = "Python 3"
language_tool = "EN"
creator = "FluzyTeck"
discord_server = "discord.gg/eWNQ46jqdC"
website = "red-tiger.000webhostapp.com"
github_tool = "github.com/fluzyteck/RedTiger-Tools"
url_config = "https://raw.githubusercontent.com/fluzyteck/RedTiger/main/Settings/Program/Config/Config.py"

